### ISSUE TITLE
Firefox randomly steals keyboard focus

### ISSUE THREAD

**Issue by antoniocorbi** [djpohly/dwl#339]
## Info
dwl's commit: HEAD
wlroots version: 0.15.1-6 (from archlinux)
## Description

Hi, I'm using firefox 107.0.1-1 from archlinux.
Sometimes (don't know how to reproduce it but I know howto solve in the mean-time) firefox steals the keyboard focus.
When this happens only the firefox window has the red (in my case) color border of selected windows and it's imposible to give focus to other windows (via the keyboard or the mouse). The rest of dwl continues working, i.e. I can switch _workspaces_ (tags), etc...

The only thing that seems to work reliably is to close firefox window and then keyboard focus starts to work normally, even if I reopen firefox...until the next random focus steal.

**Comment by sevz17** [comment]
Is it running natively on wayland?

**Comment by antoniocorbi** [comment]
> Is Firefox running natively on wayland?

Nope, On XWayland because Firfox renders bad  (at least for me) some extra  big pop-up menus (i.e. like the ones that pop-up when you click a folder with lots of urls stored in them).

I can give firefox a try in pure Wayland, but I haven't had this problem in other compositors like sway or hyprland.

**Comment by sevz17** [comment]
> > Is Firefox running natively on wayland?
> 
> Nope, It runs on XWayland because Firefox runing on pure wayland renders bad (at least for me) some extra big pop-up menus (i.e. like the ones that pop-up when you click a folder with lots of urls stored in them).

Yes, there is a problem with popups in wlroots-0.15, it has been fixed in wlroots-0.16.

> I can give firefox a try in pure Wayland, but I haven't had this problem (with firefox running on XWayland) in other compositors like sway or hyprland.

I just released 0.4-rc1 which uses wlroots-0.16, when you update to 0.16 you will be able to safely run firefox natively in wayland.

**Comment by krypciak** [comment]
Running firefox on wayland natively, dwl is up to date with the git repo,
yet this issue is still present.

**Comment by k355l3r-5yndr0m3** [comment]
I also have this problem. Although after switching firefox to run on wayland natively, I has not noticed it happened. But for librewolf, which is a fork of firefox, this still does happen. Note, I haven't configure librewolf to run natively on wayland, so this problem seems to relate to xwayland.

**Comment by 305a385** [comment]
can reproduce under Arch Linux using librewolf-bin from the AUR

I can't figure out how to set librewolf to wayland, I've tried env variables `MOZ_ENABLE_WAYLAND=1` and `GDK_BACKEND="wayland"` but about:support still shows xwayland

Funnily enough, the problem isn't happening as I write this comment but was happening 5 minutes ago (I have relaunched librewolf since then)

**Comment by 305a385** [comment]
This is presumably happening because xorg (and by extension xwayland) allows apps to steal input
